# Generated by Django 4.0.1 on 2022-01-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_member_training_delete_customer_users_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(verbose_name=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.TextField(verbose_name=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.TextField(verbose_name=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.TextField(verbose_name=50),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='first_name',
            field=models.TextField(verbose_name=50),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_name',
            field=models.TextField(verbose_name=50),
        ),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.TextField(verbose_name=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.TextField(verbose_name=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.TextField(verbose_name=50),
        ),
    ]
