# Generated by Django 4.0.1 on 2022-01-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_member_birth_date_alter_member_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.TextField(verbose_name=13),
        ),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.TextField(verbose_name=255),
        ),
    ]
