# Generated by Django 4.0.1 on 2022-01-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_user_delete_users_member_id_card_training_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trainer',
            new_name='staff',
        ),
    ]
