# Generated by Django 4.0.1 on 2022-01-27 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_rename_trainer_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='member',
            new_name='members',
        ),
        migrations.RenameModel(
            old_name='training',
            new_name='trainings',
        ),
        migrations.RenameModel(
            old_name='user',
            new_name='users',
        ),
    ]
