# Generated by Django 4.0.1 on 2022-01-28 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_rename_member_members_rename_training_trainings_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='members',
            new_name='member',
        ),
        migrations.RenameModel(
            old_name='trainings',
            new_name='training',
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
